### ISSUE TITLE
Add drawn monsters to game files

### ISSUE THREAD

**Issue by ldav99** [adrienabbey/REALLY-kinda-BAD-IDLE-GAME-Just-Kidding-The-Prequel-II#101]
I need to finish drawing the monsters first. After that we need to update the book of monsters and the background images to have the monsters copy and pasted on top.

**Comment by adrienabbey** [comment]
Draw a Geoduck Luke!

**Comment by ldav99** [comment]
Cyclops and Rock are done. Just need hobo goblin now.

**Comment by ldav99** [comment]
Finished and uploaded
