### ISSUE TITLE
Change book of monster descriptions and SFX

### ISSUE THREAD

**Issue by ldav99** [adrienabbey/REALLY-kinda-BAD-IDLE-GAME-Just-Kidding-The-Prequel-II#104]
Pictures and pages are updated just need descriptions and SFX.

**Comment by ldav99** [comment]
Descriptions changed on mosterGraphics branch. Just need SFX now.

**Comment by adrienabbey** [comment]
![image](https://github.com/adrienabbey/REALLY-kinda-BAD-IDLE-GAME-Just-Kidding-The-Prequel-II/assets/97482581/d6a9a9db-5dfa-4fd7-b488-190e2fd95e6f)
