### ISSUE TITLE
Critical Balancing Issues (Check Comments, DO NOT CLOSE)

### ISSUE THREAD

**Issue by adrienabbey** [adrienabbey/REALLY-kinda-BAD-IDLE-GAME-Just-Kidding-The-Prequel-II#106]
Like the 'Critical Bug Fixes' issue, this should focus on any balancing issues that block the player's progression, such as the unkillable Hobo Goblin that still plagues our adventurers.  This should NOT include non-critical balancing issues.

Add comments here for any balancing issues found that need to be addressed before the code freeze date of April 5th.

Do NOT close this issue until all the commented issues have been resolved!

**Comment by adrienabbey** [comment]
The Hobo Goblin is nearly unkillable.

Several ways to address this issue:
1. Increase the player starting stats.  This will be the easiest.  Or reduce the Hobo Goblin's stats.
2. Change the combat algorithm to favor the player more, and/or add additional systems that favor the player.  Magic is good, but not good enough to win this fight.
3. Reduce/remove the encounter rate.

**Comment by ldav99** [comment]
Hobogoblin is now killable.
