### ISSUE TITLE
Animated Googly Eyes

### ISSUE THREAD

**Issue by adrienabbey** [adrienabbey/REALLY-kinda-BAD-IDLE-GAME-Just-Kidding-The-Prequel-II#32]
![image](https://github.com/adrienabbey/REALLY-kinda-BAD-IDLE-GAME-Just-Kidding-The-Prequel-II/assets/97482581/30c7ad5d-b00a-49e6-a97f-8f1b0706c05c)

**Comment by adrienabbey** [comment]
https://github.com/googlesamples/android-vision/blob/master/visionSamples/googly-eyes/app/src/main/java/com/google/android/gms/samples/vision/face/googlyeyes/EyePhysics.java

**Comment by ldav99** [comment]
Muhammed was able to add these, changed assignee and closed
