### ISSUE TITLE
Autoscale GUI and add maximize/minimize screen window

### ISSUE THREAD

**Issue by MuhammedAbu** [adrienabbey/REALLY-kinda-BAD-IDLE-GAME-Just-Kidding-The-Prequel-II#91]
Get user's PC resolution, then modify GUI resolution accordingly.
Draw eyes with a relative coordinate system so they are correctly placed regardless of screen resolution, or figure out how to feed the fixed location system coordinates that are derived from current resolution to autoscaled resolution.

**Comment by adrienabbey** [comment]
Tentatively labeling this for MVP, but it should NOT be prioritized over other features!
