### ISSUE TITLE
Integrate Potions into UI

### ISSUE THREAD

**Issue by adrienabbey** [adrienabbey/REALLY-kinda-BAD-IDLE-GAME-Just-Kidding-The-Prequel-II#98]
Combat UI needs a button to use a potion, display how many potions are available.

Ensure store UI correctly handles potion buying / using / etc.

**Comment by ldav99** [comment]
There is now a button in the dungeon area for potions, it doesn't have functionality, I will open a new issue for that. Potions are displayed in character screen above combat text.
